import { useCallback } from "react";
import { format_date_to_string, parse_date_string } from "../utils/date_helpers";
import type { Pdca } from "@/data/pdca";

export function useConstruirPayloadPdca(
  pdcaActual: Pdca,
  estadoPdca: any, // We can use any or the return type of use_pdca_dialog_state
  progresoCalculado: number,
) {
  return useCallback((): Pdca => {
    return {
      ...pdcaActual,
      titulo: estadoPdca.title_value,
      area: estadoPdca.area_value,
      fase: estadoPdca.active_tab,
      problema: estadoPdca.problem_value,
      causaRaiz: estadoPdca.root_cause_value,
      acciones: estadoPdca.action_items,
      targetVsActual: estadoPdca.target_vs_actual,
      targetVsActualUnit: estadoPdca.target_vs_actual_unit,
      targetVsActualTitle: estadoPdca.target_vs_actual_title,
      targetVsActualYmin: estadoPdca.target_vs_actual_ymin,
      targetVsActualYmax: estadoPdca.target_vs_actual_ymax,
      kpiFinalResultData: estadoPdca.kpi_final_result_data,
      kpiFinalResultUnit: estadoPdca.kpi_final_result_unit,
      gembaFinalImage: estadoPdca.gemba_final_image,
      gembaFinalImages: estadoPdca.gemba_final_images,
      evidencias: estadoPdca.evidence_files,
      kpiDocuments: estadoPdca.kpi_document_files,
      paretoDataMap: estadoPdca.pareto_data_map,
      paretoDrillDowns: estadoPdca.pareto_drill_downs,
      paretoUnit: estadoPdca.pareto_unit,
      paretoTitles: estadoPdca.pareto_titles,
      vpoCheckpoints: estadoPdca.vpo_checkpoints,
      definicionMeta: estadoPdca.definition_goal,
      participantes: estadoPdca.participants_data,
      equipo: estadoPdca.team_members,
      ishikawas: estadoPdca.ishikawas,
      fiveWhysTables: estadoPdca.five_whys_tables,
      impactMatrix: estadoPdca.impact_matrix,
      hasFlavorCorrelation: estadoPdca.has_flavor_correlation,
      flavorCorrelationData: estadoPdca.flavor_correlation_data,
      statisticalAnalysisFiles: estadoPdca.statistical_analysis_files,
      hasGopThemes: estadoPdca.has_gop_themes,
      has_gop_themes: estadoPdca.has_gop_themes,
      gopThemesData: estadoPdca.gop_themes_data,
      gop_themes_data: estadoPdca.gop_themes_data,
      processMappingImage: estadoPdca.process_mapping_files?.[0] || null,
      processMappingFiles: estadoPdca.process_mapping_files,
      sipocMapFiles: estadoPdca.sipoc_map_files,
      problemTimelineOption: estadoPdca.problem_timeline_option,
      problemTimelineFilter: estadoPdca.problem_timeline_filter,
      problemTimelineEvents: estadoPdca.problem_timeline_events,
      itfR2d2Evaluation: estadoPdca.itf_r2d2_evaluation,
      baselineImage: estadoPdca.baseline_image,
      tablaEstandarizacion: estadoPdca.tabla_estandarizacion,
      tablaEstandarizacionVpo: estadoPdca.tabla_estandarizacion_vpo,
      resultadosFinales: estadoPdca.resultados_finales,
      kpiTreeFocoImage: estadoPdca.kpi_tree_foco_image,
      evidenciasSolucion: estadoPdca.evidencias_solucion,
      hasMapeoProceso: estadoPdca.has_mapeo_proceso,
      mapeoProcesoImage: estadoPdca.mapeo_proceso_image,
      mapeoProcesoDesc: estadoPdca.mapeo_proceso_desc || undefined,
      rendimiento_actual_pis: estadoPdca.rendimiento_actual_pis,
      rendimiento_actual_image: estadoPdca.rendimiento_actual_image,
      coleccionDatos: estadoPdca.coleccion_datos,
      especificacionProcesosText: estadoPdca.especificacion_procesos_text ?? undefined,
      especificacionProcesosImage: estadoPdca.especificacion_procesos_image,
      finalTimeSeriesTitle: estadoPdca.final_time_series_title,
      finalTimeSeriesData: estadoPdca.final_time_series_data,
      finalTimeSeriesUnit: estadoPdca.final_time_series_unit,
      finalTimeSeriesYmin: estadoPdca.final_time_series_ymin,
      finalTimeSeriesYmax: estadoPdca.final_time_series_ymax,
      currentTimesTitle: estadoPdca.current_times_title,
      ishikawaConceptos: estadoPdca.ishikawa_conceptos,
      informacionAdicionalFiles: estadoPdca.informacion_adicional_files,
      vozConsumidor: estadoPdca.voz_consumidor,
      analisisRiesgosProyecto: estadoPdca.analisis_riesgos_proyecto,
      conclusionesCausaRaiz: estadoPdca.conclusiones_causa_raiz,
      pruebasEjecutadas: estadoPdca.pruebas_ejecutadas,
      nuevoPerformance: estadoPdca.nuevo_performance,
      nuevo_performance_image: estadoPdca.nuevo_performance_image,
      nuevo_pareto_image: estadoPdca.nuevo_pareto_image,
      nuevo_pareto_drill_downs: estadoPdca.nuevo_pareto_drill_downs,
      nuevo_pareto_data_map: estadoPdca.nuevo_pareto_data_map,
      nuevo_pareto_unit: estadoPdca.nuevo_pareto_unit,
      nuevo_pareto_titles: estadoPdca.nuevo_pareto_titles,
      nueva_correlacion_image: estadoPdca.nueva_correlacion_image,
      has_nueva_correlacion: estadoPdca.has_nueva_correlacion,
      nueva_correlacion_data: estadoPdca.nueva_correlacion_data,
      analisisRiesgosEstandarizacion: estadoPdca.analisis_riesgos_estandarizacion,
      conclusionesFinales: estadoPdca.conclusiones_finales,
      conclusionesStoryboardImage: estadoPdca.conclusiones_storyboard_image,
      conclusionesKpiData: estadoPdca.conclusiones_kpi_data ?? undefined,
      conclusionesPiItems: estadoPdca.conclusiones_pi_items ?? undefined,
      sops_documentos_image: estadoPdca.sops_documentos_image,
      plan_entrenamiento_image: estadoPdca.plan_entrenamiento_image,
      plan_control_image: estadoPdca.plan_control_image,
      lecciones_aprendidas: estadoPdca.lecciones_aprendidas,
      benchmarkImage: estadoPdca.benchmark_image,
      comentarios: estadoPdca.comments_list,
      historial: estadoPdca.history_events,
      completedSteps: Array.from(estadoPdca.completed_steps),
      naSteps: Array.from(estadoPdca.na_steps),
      completedPhases: Array.from(estadoPdca.completed_phases),
      progreso: progresoCalculado,
      fechaFinalizacion: estadoPdca.deadline_date
        ? format_date_to_string(estadoPdca.deadline_date)
        : pdcaActual.fechaFinalizacion === "Sin límite" ||
            pdcaActual.fechaFinalizacion === "Sin lÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â­mite" // handle corrupted string
          ? "Sin límite"
          : pdcaActual.fechaFinalizacion && !parse_date_string(pdcaActual.fechaFinalizacion)
            ? pdcaActual.fechaFinalizacion
            : "",
      autor: estadoPdca.author_name,
      autorEmail: estadoPdca.author_email,
      asignados: estadoPdca.assigned_users,
      actualizado: new Date().toLocaleDateString("es-ES", {
        day: "numeric",
        month: "short",
        year: "numeric",
      }),
    };
  }, [pdcaActual, estadoPdca, progresoCalculado]);
}
